import type {
  Alert,
  AlertHistoryEntry,
  AlertState,
  AuditEntry,
  ActivityEvent,
  Defect,
  DefectSubmitResponse,
  KnownFix,
  Role,
  Severity,
  SummaryMetrics,
  Ticket,
  NCR,
  TrendPoint,
} from '@/types';
import {
  STATIONS,
  PRODUCTS,
  DEFECT_CODES,
  KNOWN_FIXES,
  SEED_DEFECTS,
  SEED_ALERTS,
  SEED_AUDIT,
  SEED_ACTIVITY,
} from './seed';

const RULE_VERSION = 'v3';
const DEFAULT_THRESHOLD = 3;
const DEFAULT_WINDOW = 30;

interface MockState {
  defects: Defect[];
  alerts: Alert[];
  tickets: Ticket[];
  ncrs: NCR[];
  audit: AuditEntry[];
  activity: ActivityEvent[];
  history: AlertHistoryEntry[];
  thresholdN: number;
  windowT: number;
  seq: number;
  currentUser: Role;
}

const state: MockState = {
  defects: [...SEED_DEFECTS],
  alerts: [...SEED_ALERTS],
  tickets: [],
  ncrs: [],
  audit: [...SEED_AUDIT],
  activity: [...SEED_ACTIVITY],
  history: [
    {
      id: 'H-001',
      alertId: 'ALT-1041',
      actor: 'System',
      fromState: '—',
      toState: 'OPEN',
      note: 'Alert auto-generated by pattern rule',
      timestamp: SEED_ALERTS[0].createdAt,
    },
    {
      id: 'H-002',
      alertId: 'ALT-1041',
      actor: 'Field Engineer',
      fromState: 'OPEN',
      toState: 'ACKNOWLEDGED',
      note: 'Acknowledged, investigating scanner issue',
      timestamp: new Date(Date.now() - 18 * 60_000).toISOString(),
    },
  ],
  thresholdN: DEFAULT_THRESHOLD,
  windowT: DEFAULT_WINDOW,
  seq: 3000,
  currentUser: 'Field Engineer',
};

function nextId(prefix: string): string {
  state.seq++;
  return `${prefix}-${state.seq}`;
}

function now(): string {
  return new Date().toISOString();
}

function severityForCount(count: number, threshold: number): Severity {
  if (count >= threshold + 2) return 'CRITICAL';
  if (count >= threshold + 1) return 'HIGH';
  if (count >= threshold) return 'MEDIUM';
  return 'NORMAL';
}

function addAudit(actor: string, entity: string, action: string, details: string) {
  state.audit.unshift({
    id: nextId('AUD'),
    timestamp: now(),
    actor,
    entity,
    action,
    details,
  });
}

function addActivity(type: ActivityEvent['type'], message: string, actor: string) {
  state.activity.unshift({
    id: nextId('ACT'),
    type,
    message,
    timestamp: now(),
    actor,
  });
  if (state.activity.length > 50) state.activity.length = 50;
}

/**
 * Core pattern-detection rule engine (brief section 7).
 *
 * Call this AFTER the triggering defect has already been unshifted into
 * state.defects, so `matching` naturally includes it -- count is exactly
 * `matching.length`, no manual "+1" needed (a +1 here would double-count).
 *
 * Evaluates using EVENT time (each defect's own occurredAt), never
 * Date.now(), so delayed/offline submissions are handled predictably
 * (brief 4.2). Idempotent: reuses an existing non-resolved alert for the
 * same station+defectCode pattern instead of creating a duplicate
 * alert/ticket/NCR (brief 4.4 / 9).
 */
function classify(stationId: string, defectCode: string, occurredAt: string): DefectSubmitResponse {
  const windowMs = state.windowT * 60_000;
  const occurredTs = new Date(occurredAt).getTime();

  const matching = state.defects.filter(
    (d) =>
      d.stationId === stationId &&
      d.defectCode === defectCode &&
      new Date(d.occurredAt).getTime() >= occurredTs - windowMs &&
      new Date(d.occurredAt).getTime() <= occurredTs,
  );

  const count = matching.length;
  const knownFix = KNOWN_FIXES.find((f) => f.code === defectCode);
  const firstOcc = matching.reduce(
    (min, d) => (d.occurredAt < min ? d.occurredAt : min),
    matching[0]?.occurredAt ?? occurredAt,
  );

  if (count >= state.thresholdN) {
    const severity = severityForCount(count, state.thresholdN);

    // Idempotency: reuse the existing open alert for this exact pattern instead
    // of creating a duplicate alert/ticket/NCR.
    const existingAlert = state.alerts.find(
      (a) => a.stationId === stationId && a.defectCode === defectCode && a.state !== 'RESOLVED',
    );

    if (existingAlert) {
      existingAlert.count = count;
      existingAlert.severity = severity;
      existingAlert.latestOccurrence = occurredAt;
      addAudit('System', 'Alert', 'UPDATE', `${existingAlert.id} updated (count=${count}) for existing ${defectCode} pattern at ${stationId}`);
      addActivity('alert_opened', `${existingAlert.id} updated: ${defectCode} at ${stationId} now at ${count}/${state.thresholdN}`, 'System');
      return {
        classification: 'SYSTEMIC',
        severity,
        stationId,
        defectCode,
        occurrenceCount: count,
        windowMinutes: state.windowT,
        alertId: existingAlert.id,
        ticketId: existingAlert.ticketId,
        ncrId: existingAlert.ncrId,
        recommendedAction: existingAlert.recommendedAction,
      };
    }

    const alertId = nextId('ALT');
    const ticketId = nextId('TKT');
    const ncrId = nextId('NCR');

    const alert: Alert = {
      id: alertId,
      severity,
      stationId,
      defectCode,
      count,
      threshold: state.thresholdN,
      windowMinutes: state.windowT,
      firstOccurrence: firstOcc,
      latestOccurrence: occurredAt,
      state: 'OPEN',
      ticketId,
      ncrId,
      ruleVersion: RULE_VERSION,
      recommendedAction:
        knownFix?.documentedFix ??
        `Pause affected operation and investigate ${defectCode} at ${stationId}.`,
      containment: '',
      correctiveAction: '',
      ncrStatus: 'DRAFT',
      createdAt: now(),
    };

    state.alerts.unshift(alert);
    state.tickets.push({
      id: ticketId,
      alertId,
      defectCode,
      stationId,
      status: 'OPEN',
      createdAt: now(),
    });
    state.ncrs.push({
      id: ncrId,
      alertId,
      containment: '',
      correctiveAction: '',
      status: 'DRAFT',
      createdAt: now(),
    });

    addAudit('System', 'Alert', 'OPEN', `Alert ${alertId} opened for ${defectCode} at ${stationId}`);
    addActivity('alert_opened', `Alert ${alertId} opened for ${defectCode} at ${stationId}`, 'System');
    addAudit('System', 'Ticket', 'CREATE', `Ticket ${ticketId} created for ${alertId}`);
    addActivity('ticket_created', `Ticket ${ticketId} created`, 'System');
    addAudit('System', 'NCR', 'CREATE', `NCR ${ncrId} created for ${alertId}`);
    addActivity('ncr_created', `NCR ${ncrId} created for ${alertId}`, 'System');

    return {
      classification: 'SYSTEMIC',
      severity,
      stationId,
      defectCode,
      occurrenceCount: count,
      windowMinutes: state.windowT,
      alertId,
      ticketId,
      ncrId,
      recommendedAction: alert.recommendedAction,
    };
  }

  if (knownFix) {
    return {
      classification: 'KNOWN',
      severity: 'MEDIUM',
      stationId,
      defectCode,
      occurrenceCount: count,
      windowMinutes: state.windowT,
      knownFix,
      currentCount: count,
      windowThreshold: state.thresholdN,
    };
  }

  const ticketId = nextId('TKT');
  state.tickets.push({
    id: ticketId,
    alertId: '',
    defectCode,
    stationId,
    status: 'OPEN',
    createdAt: now(),
  });
  addAudit('System', 'Ticket', 'CREATE', `Investigation ticket ${ticketId} created for ${defectCode}`);
  addActivity('ticket_created', `Investigation ticket ${ticketId} created`, 'System');

  return {
    classification: 'UNKNOWN',
    severity: 'MEDIUM',
    stationId,
    defectCode,
    occurrenceCount: count,
    windowMinutes: state.windowT,
    ticketId,
  };
}

const VALID_TRANSITIONS: Record<AlertState, AlertState | null> = {
  OPEN: 'ACKNOWLEDGED',
  ACKNOWLEDGED: 'INVESTIGATING',
  INVESTIGATING: 'CONTAINED',
  CONTAINED: 'RESOLVED',
  RESOLVED: null,
};

export const mockApi = {
  async logDefect(input: {
    stationId: string;
    productId: string;
    serialNumber: string;
    defectCode: string;
    description: string;
    photoDataUrl?: string;
    occurredAt: string;
    actor?: string;
  }): Promise<DefectSubmitResponse> {
    await delay(400);

    // Dedup check happens BEFORE inserting the new defect, against the
    // existing state only -- otherwise the just-inserted defect would always
    // match itself and every submission would look like a duplicate.
    const duplicate = state.defects.find(
      (d) =>
        d.stationId === input.stationId &&
        d.serialNumber === input.serialNumber &&
        d.defectCode === input.defectCode &&
        Date.now() - new Date(d.loggedAt).getTime() < 60_000,
    );

    if (duplicate) {
      const windowMs = state.windowT * 60_000;
      const occurredTs = new Date(input.occurredAt).getTime();
      const currentCount = state.defects.filter(
        (d) =>
          d.stationId === input.stationId &&
          d.defectCode === input.defectCode &&
          new Date(d.occurredAt).getTime() >= occurredTs - windowMs &&
          new Date(d.occurredAt).getTime() <= occurredTs,
      ).length;
      return {
        classification: 'NORMAL',
        severity: 'NORMAL',
        stationId: input.stationId,
        defectCode: input.defectCode,
        occurrenceCount: currentCount,
        windowMinutes: state.windowT,
        duplicate: true,
      };
    }

    const defect: Defect = {
      id: nextId('DEF'),
      stationId: input.stationId,
      productId: input.productId,
      serialNumber: input.serialNumber,
      defectCode: input.defectCode,
      description: input.description,
      photoDataUrl: input.photoDataUrl,
      occurredAt: input.occurredAt,
      loggedAt: now(),
      loggedBy: input.actor ?? state.currentUser,
    };
    state.defects.unshift(defect);

    addAudit(defect.loggedBy, 'Defect', 'LOG', `${defect.id} logged at ${input.stationId} (${input.defectCode})`);
    addActivity('defect_logged', `${defect.id} logged at ${input.stationId} (${input.defectCode})`, defect.loggedBy);

    return classify(input.stationId, input.defectCode, input.occurredAt);
  },

  async getDefects(stationId?: string): Promise<Defect[]> {
    await delay(150);
    if (stationId) return state.defects.filter((d) => d.stationId === stationId);
    return [...state.defects];
  },

  async getAlerts(filters?: { state?: AlertState; severity?: Severity; stationId?: string; defectCode?: string }): Promise<Alert[]> {
    await delay(150);
    let result = [...state.alerts];
    if (filters?.state) result = result.filter((a) => a.state === filters.state);
    if (filters?.severity) result = result.filter((a) => a.severity === filters.severity);
    if (filters?.stationId) result = result.filter((a) => a.stationId === filters.stationId);
    if (filters?.defectCode) result = result.filter((a) => a.defectCode === filters.defectCode);
    return result;
  },

  async getAlert(id: string): Promise<Alert | undefined> {
    await delay(100);
    return state.alerts.find((a) => a.id === id);
  },

  async acknowledgeAlert(id: string, actor: string, note: string): Promise<Alert | undefined> {
    await delay(200);
    const alert = state.alerts.find((a) => a.id === id);
    if (!alert) return undefined;
    if (alert.state !== 'OPEN') return alert;
    const oldState = alert.state;
    alert.state = 'ACKNOWLEDGED';
    addHistory(id, actor, oldState, alert.state, note);
    addAudit(actor, 'Alert', 'TRANSITION', `${id} ${oldState} -> ${alert.state}`);
    addActivity('state_changed', `${id} ${oldState} -> ${alert.state}`, actor);
    return alert;
  },

  async transitionAlert(id: string, target: AlertState, actor: string, note: string): Promise<Alert | undefined> {
    await delay(200);
    const alert = state.alerts.find((a) => a.id === id);
    if (!alert) return undefined;
    const expected = VALID_TRANSITIONS[alert.state];
    if (expected !== target) return alert;
    const oldState = alert.state;
    alert.state = target;
    addHistory(id, actor, oldState, target, note);
    addAudit(actor, 'Alert', 'TRANSITION', `${id} ${oldState} -> ${target}`);
    addActivity('state_changed', `${id} ${oldState} -> ${target}`, actor);
    return alert;
  },

  async getEvidence(alertId: string): Promise<Defect[]> {
    await delay(150);
    const alert = state.alerts.find((a) => a.id === alertId);
    if (!alert) return [];
    const windowMs = alert.windowMinutes * 60_000;
    const firstTs = new Date(alert.firstOccurrence).getTime();
    return state.defects.filter(
      (d) =>
        d.stationId === alert.stationId &&
        d.defectCode === alert.defectCode &&
        Math.abs(new Date(d.occurredAt).getTime() - firstTs) < windowMs + 60_000,
    );
  },

  async getHistory(alertId: string): Promise<AlertHistoryEntry[]> {
    await delay(100);
    return state.history.filter((h) => h.alertId === alertId);
  },

  async getKnownFix(code: string): Promise<KnownFix | undefined> {
    await delay(100);
    return KNOWN_FIXES.find((f) => f.code === code);
  },

  async getAllKnownFixes(): Promise<KnownFix[]> {
    await delay(100);
    return [...KNOWN_FIXES];
  },

  async markFixHelpful(code: string): Promise<KnownFix | undefined> {
    await delay(100);
    const fix = KNOWN_FIXES.find((f) => f.code === code);
    if (fix) fix.helpfulCount++;
    return fix;
  },

  async createTicket(input: { alertId?: string; defectCode: string; stationId: string }): Promise<Ticket> {
    await delay(200);
    const ticket: Ticket = {
      id: nextId('TKT'),
      alertId: input.alertId ?? '',
      defectCode: input.defectCode,
      stationId: input.stationId,
      status: 'OPEN',
      createdAt: now(),
    };
    state.tickets.push(ticket);
    addAudit(state.currentUser, 'Ticket', 'CREATE', `Ticket ${ticket.id} created`);
    addActivity('ticket_created', `Ticket ${ticket.id} created`, state.currentUser);
    return ticket;
  },

  async updateNcr(alertId: string, containment: string, correctiveAction: string): Promise<Alert | undefined> {
    await delay(200);
    const alert = state.alerts.find((a) => a.id === alertId);
    if (!alert) return undefined;
    alert.containment = containment;
    alert.correctiveAction = correctiveAction;
    if (alert.ncrStatus === 'DRAFT') alert.ncrStatus = 'IN_PROGRESS';
    addAudit(state.currentUser, 'NCR', 'UPDATE', `NCR for ${alertId} updated`);
    return alert;
  },

  async getMetrics(): Promise<SummaryMetrics> {
    await delay(100);
    const openAlerts = state.alerts.filter((a) => a.state !== 'RESOLVED').length;
    const todayStart = new Date();
    todayStart.setHours(0, 0, 0, 0);
    const systemicToday = state.alerts.filter((a) => new Date(a.createdAt) >= todayStart).length;
    const affectedUnits = new Set(
      state.alerts.flatMap((a) =>
        state.defects
          .filter((d) => d.stationId === a.stationId && d.defectCode === a.defectCode)
          .map((d) => d.serialNumber),
      ),
    ).size;
    const unresolvedTickets = state.tickets.filter((t) => t.status !== 'RESOLVED').length;
    return { openAlerts, systemicPatternsToday: systemicToday, affectedUnits, unresolvedTickets };
  },

  async getStationRisk(): Promise<{ stationId: string; count: number; threshold: number }[]> {
    await delay(100);
    const windowMs = state.windowT * 60_000;
    return STATIONS.map((st) => {
      const count = state.defects.filter(
        (d) => d.stationId === st.id && Date.now() - new Date(d.occurredAt).getTime() < windowMs,
      ).length;
      return { stationId: st.id, count, threshold: state.thresholdN };
    });
  },

  async getTrend(stationId: string): Promise<TrendPoint[]> {
    await delay(200);
    const windowMs = state.windowT * 60_000;
    const buckets: Record<string, TrendPoint> = {};
    const codes = new Set(state.defects.filter((d) => d.stationId === stationId).map((d) => d.defectCode));

    for (let i = 9; i >= 0; i--) {
      const ts = Date.now() - i * (windowMs / 3);
      const label = new Date(ts).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });
      const key = label;
      buckets[key] = { timestamp: new Date(ts).toISOString(), label };
      for (const c of codes) buckets[key][c] = 0;
    }

    for (const d of state.defects) {
      if (d.stationId !== stationId) continue;
      const label = new Date(d.occurredAt).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });
      if (buckets[label] && typeof buckets[label][d.defectCode] === 'number') {
        (buckets[label][d.defectCode] as number)++;
      }
    }

    return Object.values(buckets);
  },

  async getActivity(): Promise<ActivityEvent[]> {
    await delay(100);
    return state.activity.slice(0, 15);
  },

  async getAudit(filters?: { entity?: string; actor?: string }): Promise<AuditEntry[]> {
    await delay(100);
    let result = [...state.audit];
    if (filters?.entity) result = result.filter((a) => a.entity === filters.entity);
    if (filters?.actor) result = result.filter((a) => a.actor === filters.actor);
    return result;
  },

  async getSettings(): Promise<{ thresholdN: number; windowT: number; ruleVersion: string }> {
    await delay(50);
    return { thresholdN: state.thresholdN, windowT: state.windowT, ruleVersion: RULE_VERSION };
  },

  async saveSettings(thresholdN: number, windowT: number): Promise<void> {
    await delay(200);
    state.thresholdN = thresholdN;
    state.windowT = windowT;
    addAudit(state.currentUser, 'Settings', 'UPDATE', `Threshold=${thresholdN}, Window=${windowT}min`);
  },

  async runDemoScenario(): Promise<void> {
    const stationId = 'ST-07';
    const defectCode = 'TORQUE_LOW';
    const productId = 'PUMP-X2';

    for (let i = 0; i < 3; i++) {
      await delay(800);
      const serial = `PX2-DEMO-${Date.now()}`;
      const defect: Defect = {
        id: nextId('DEF'),
        stationId,
        productId,
        serialNumber: serial,
        defectCode,
        description: `Demo scenario: torque reading below spec on unit ${serial}`,
        occurredAt: now(),
        loggedAt: now(),
        loggedBy: state.currentUser,
      };
      state.defects.unshift(defect);
      addAudit(state.currentUser, 'Defect', 'LOG', `${defect.id} logged at ${stationId} (${defectCode})`);
      addActivity('defect_logged', `${defect.id} logged at ${stationId} (${defectCode})`, state.currentUser);

      if (i === 2) {
        classify(stationId, defectCode, defect.occurredAt);
      }
    }
  },

  getStations() {
    return STATIONS;
  },
  getProducts() {
    return PRODUCTS;
  },
  getDefectCodes() {
    return DEFECT_CODES;
  },
  getKnownFixes() {
    return KNOWN_FIXES;
  },
  setCurrentUser(role: Role) {
    state.currentUser = role;
  },
  getCurrentUser(): Role {
    return state.currentUser;
  },
};

function addHistory(alertId: string, actor: string, fromState: AlertState | '—', toState: AlertState, note: string) {
  state.history.unshift({
    id: nextId('H'),
    alertId,
    actor,
    fromState,
    toState,
    note,
    timestamp: now(),
  });
}

function delay(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
